version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: moohii
    restart: unless-stopped
    working_dir: /var/www/moohii
    tty: true
    depends_on:
      - mysql
    volumes:
      - ./app:/var/www/moohii
    ports:
      - "9010:9000"
    networks:
      - moohii

  mysql:
    image: mysql:5.7
    container_name: moohii_mysql
    restart: unless-stopped
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: moohii
      MYSQL_USER: moohii
      MYSQL_PASSWORD: moohii
      MYSQL_ROOT_PASSWORD: moohii
    networks:
      - moohii

  nginx:
    image: nginx:alpine
    container_name: moohii_nginx
    restart: unless-stopped
    ports:
      - "8010:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/moohii
    depends_on:
      - app
    networks:
      - moohii

  npm:
    build:
      context: .
      dockerfile: ./docker/nodejs/Dockerfile
    container_name: moohii_npm
    restart: unless-stopped
    volumes:
      - ./app:/var/www/moohii
    networks:
      - moohii

networks:
  moohii:
    driver: bridge